name: Build and Push Dockerhub

on:
  workflow_dispatch:
    
jobs:
  login-build-push:
    name: Login Build Push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ngix:latest .

      - uses: azure/container-scan@v0
        with:
          image-name: ${{ secrets.DOCKER_USERNAME }}/ngix:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}        
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ngix:latest
      
      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     pull: true
      #     push: true
      #     file: ./Dockerfile 
      #     tags: |
      #       ${{ secrets.DOCKER_USERNAME }}/ngix:latest